### ISSUE TITLE
[Request] Remove user join message

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#107]
Is it possible that the TLG_JoinCaptchaBot also can remove/clean the join notification text if he kick or ban the user??

<img width="283" alt="Bildschirmfoto 2021-07-08 um 20 57 18" src="https://user-images.githubusercontent.com/35367117/124976951-33615180-e030-11eb-85c4-4b95677e7007.png">

**Comment by J-Rios** [comment]
Hi, the Bot was also deleting this messages, but after [this issue](https://github.com/J-Rios/TLG_JoinCaptchaBot/issues/103), that was changed. The reason is that new Telegram event to detect new users joins changes how we can detect the join and I'm not sure if we can now detect the message ID of the join message, that is needed to be removed...

Let's keep this issue open until I check if there is any way to get the message ID again without going back to old (and maybe future deprecated) way of detect users joins...

**Comment by J-Rios** [comment]
## Context

The issue is related to next Telegram Bot API change:

> ⚠️ WARNING! ⚠️
> Service messages about non-bot users joining the chat will be soon removed from large groups. We recommend using the “chat_member” update as a replacement.

Telegram recommend to use the new "chat_member" update instead the "message" update to detect new users joins. So this change was done in CaptchaBot (needed to detect new users in large groups). However, with this new update, we didn't receive the message ID of "user X join the group" message, that is needed to remove that message after the user is kicked, so the message remains after user kick/ban.

## Thinking about

I have try to detect both updates in code (the "message" update and the "chat_member" one), but it seems that Telegram sends first the "chat_member" update and then the "message" update:

```bash
{
    "ok": true,
    "result": [
        {
            "update_id": 193051648,
            "chat_member": {
                ...
            }
        },
        {
            "update_id": 193051649,
            "message": {
                ...
            }
        }
    ]
}
```

Due we didn't receive the "message" info in the same update or before the "chat_member", and we didn't know if we are going to receive that message (it doesn't exists in large groups) we could try to delay the "chat_member" receive event (what is not a good idea), or add both "chat_member" and "message" updates to an event queues that should be handled by a new thread to detect when we receive both updates (and it's certainly not a good idea due it will be complex to implement and directly impact RAM usage and add a big risk that could affect other Bot functionalities. Too much complex and risky for a little fix)...

**Comment by J-Rios** [comment]
Done some workaround to get this functionality back (remove "User joined the group" messages after kick/ban):
https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/227b5df1b9e752f3a06779bd57fac10d4c655fcb

It works, but I have to remove the "async" handling of users joins events handlers and I'm not sure if it can cause some secondary troubles with large scalability. We will see if it is ok after I deploy the new version with this changes...

**Comment by J-Rios** [comment]
Seems that CPU usage increase a bit, but it is not a big issue so... Feature restored successfully! User join messages are removed again when user is kicked or banned :)
