### ISSUE TITLE
[Request] Hide Group Bots Commands Button "/"

### ISSUE THREAD

**Issue by antikruk** [J-Rios/TLG_JoinCaptchaBot#123]
Add the feature to hide button "/" for users.

**Comment by J-Rios** [comment]
Hi,

Assuming that you mean the "/" button that appears inside groups and show the available commands of the Bot...

This button comes from Telegram and is Bot account specific configuration that just can be modify manually by the Bot account owner through @BotFather. It means that it is not in Bot source code and can't be modified from Bot, neither make it configurable to hide/show on specific groups, due this is just configured globally for the Bot account for all groups :(

Current Bot accounts that I own have configured just 4 commands (/help, /commands, /language and /about) and this button with that commands are configured because it is useful for some situations.

Regards.

**Comment by J-Rios** [comment]
So, to make it hide/show configurable for each specific groups, we need to wait/request Telegram that they add some way to hide that button inside the group settings, or add some way to configure that from Bot API for each specific group.

**Comment by antikruk** [comment]
Maybe it's better to remove it?  Manual input is enough for the administrator.  When users constantly click on it, the chat becomes cluttered.

**Comment by J-Rios** [comment]
Well, in my opinion it is a useful button to allow no experienced users of telegram to at least reach how to send the basic commands like /help or /commands...

Due this is a Bot used by thousand of users and not everyone would want to hide that, I won't change it unless there is a good reason or a good number of users requesting it. i.e. come with some poll where more than 500 members that really wants to hide the button and then it will be hide.

**Comment by DanyGee** [comment]
I would also like to remove these commands from group.
Unexperienced users are simply checking the command and cluttering the chat.

**Comment by J-Rios** [comment]
Due it is not related to Bot code and just a configuration of deployed Bot accounts through Botfather, this issue will be closed.
