### ISSUE TITLE
[Question] Docker make shows warnings

### ISSUE THREAD

**Issue by SA7BNT** [J-Rios/TLG_JoinCaptchaBot#134]
Hallo, 

always running in at 

>  ---> Running in 41b0ea347812
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package perl-modules-5.28.
(Reading database ... 6840 files and directories currently installed.)
Preparing to unpack .../0-perl-modules-5.28_5.28.1-6+deb10u1_all.deb ...

and

> Installing collected packages: tzdata, backports.zoneinfo, pytz-deprecation-shim, tzlocal, six, pytz, tornado, Pillow, certifi, APScheduler, python-telegram-bot, multicolorcaptcha
  WARNING: The script multicolorcaptchademo is installed in '/srv/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed APScheduler-3.6.3 Pillow-8.3.2 backports.zoneinfo-0.2.1 certifi-2021.10.8 multicolorcaptcha-1.1.3 python-telegram-bot-13.5 pytz-2021.3 pytz-deprecation-shim-0.1.0.post0 six-1.16.0 tornado-6.1 tzdata-2021.4 tzlocal-4.0.1
WARNING: You are using pip version 21.0.1; however, version 21.3 is available.
You should consider upgrading via the '/usr/local/bin/python3 -m pip install --upgrade pip' command.
rm -rf /srv/app/.gitmodules /srv/app/.gitignore /srv/app/.git /srv/app/.github 
Removing intermediate container 71c0affeffb2

If im looking im running

>  pip --version
pip 21.3 from /home/sa7bnt/.local/lib/python3.9/site-packages/pip (python 3.9)

Can you help me out?

**Comment by J-Rios** [comment]
Hi,

That two warnings doesn't matter...

The first one just point out that a demo script included in multicolorcaptcha library is placed on a directory that you don't have in system PATH enviroment variable, but that script is not needed and you won't call it:

```bash
 WARNING: The script multicolorcaptchademo is installed in '/srv/.local/bin' which is not on PATH.
```

The second one just point that there is a newer version for pip module, and again it doesn't matter:

```bash
 WARNING: You are using pip version 21.0.1; however, version 21.3 is available.
```

At last, when you check manually your pip version, note that it is not the pip that is running for the Docker container, that's why the version doesn't match the warning.

Regards.
