### ISSUE TITLE
[Question] /disable command not working at /connect?

### ISSUE THREAD

**Issue by IO-Err** [J-Rios/TLG_JoinCaptchaBot#139]
Hi,

Just configured your bot, everything is working well inside a group chat(commands,enable/disable,etc) but I can't connect to group from bot's private chat, private chat log:
- /connect -xxxxxx
- Connected to group -xxxxxx. Now you can configure group captcha settings from private.
- /disable
- This command cannot be used in private chat unless you make a connection (/connect) to configure some group.

Bot running in docker container, logs doesn't have any errors.

Many thanks!

**Comment by J-Rios** [comment]
Hello,

The connections to groups seems working ok, but commands **/enable** and **/disable** are forbidden to be used from private chat, and this behavior is expected (these commands are disabled from private to avoid group Admins trolling to other Admins by disabling Bot functionality from private).

The real issue is just the text showed by the Bot, it should be modified to something just like "This command cannot be used in private chat.", instead telling about a connection needed... Will be fixed for next Bot version update ;)

Regards.

**Comment by J-Rios** [comment]
Fixed in commit:
https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/eb0aca4cbe93d1e6f5055c51bec914a2dd40c8cd
