### ISSUE TITLE
Trigger bot on add user

### ISSUE THREAD

**Issue by DonQuixote202** [J-Rios/TLG_JoinCaptchaBot#184]
I manage a private group to which members are invited and added. The Join Captcha Bot isn't being triggered when folks join
1. by being added by an admin,
2. by following a single-use link, or
3. by following an admin-approval-required link.

Can the bot trigger on 1 or 3, please?

**Comment by J-Rios** [comment]
Hello,

Here is some info regarding your points:

1 - This is intentional and expected behaviour for the majority of the people. If an Admin add a new member, that user could not be online on that moment, and then it will fail the captcha, also an Admin is considered a user to trust, it shouldn't going to add spam bots the group.

2 & 3 - That should work, maybe an issue with your deploy or configuration of the Bot in the group. Remember that you need to add Admin rights to the Bot for ban users and remove messages in order to make it work properly (also Botfather Group Privacy disabled in order to make the Bot receive messages that are not responses neither commands).

Best Regards :)

**Comment by DonQuixote202** [comment]
Thanks. Options 2 and 3 do not work. The only admin permission the bot does not have is posting anonymously.

How do I /setprivacy for @join_captcha_bot with @BotFather?

Group Configuration:
————————————————
{
    "Captcha_Chars_Mode": "nums",
    "Captcha_Difficulty_Level": 3,
    "Captcha_Time": 300,
    "Enabled": false,
    "Ignore_List": [],
    "Language": "EN",
    "Link": "Unknown",
    "Poll_A": [
        "",
        "",
        "",
        "",
        "",
        ""
    ],
    "Poll_C_A": 0,
    "Poll_Q": "",
    "RM_All_Msg": false,
    "Restrict_Non_Text": 0,
    "Rm_Result_Msg": false,
    "Rm_Welcome_Msg": false,
    "Title": "Group Name",
    "URL_Enabled": true,
    "Welcome_Msg": "\\[From the moderators\\]\n\nThis is a periodic reminder for the group as a whole\\. Please adhere to the guidelines: http://tinyurl\\.com/\\.\n\nIf you see a problem or have questions about how to use the group, contact the moderators\\.",
    "Welcome_Time": 60
}

**Comment by DonQuixote202** [comment]
Here's a screenshot of @BotFsther telling me I can't /setprivacy on @join_captcha_bot.

![Screenshot_20230620_070544_Telegram](https://github.com/J-Rios/TLG_JoinCaptchaBot/assets/136866931/3616fc75-d581-41d0-b986-af31dec43d57)

**Comment by J-Rios** [comment]
Closing due no feedback
