### ISSUE TITLE
[Request] Support hcaptcha

### ISSUE THREAD

**Issue by posix4e** [J-Rios/TLG_JoinCaptchaBot#23]
If you add hcaptcha support your users can be paid. We are recaptcha compatible where it matters

**Comment by J-Rios** [comment]
Hi,

HCaptcha is an interesting platform...

I use a rudimentary and custom captcha generation mechanism to avoid standarized and masive used captchas platforms, like recaptcha, where there is a lot of captcha solver libraries around.

I know that my captchas implementation are really easy to solve using a good OCR or a trained neural network, if some "bad" user want to create usersbots to solve them, it can be done, however I bet for the use of custom captchas because I know that to solve it, they must create bots that download the telegram image first, make the recognizion, and then response, it is much more un-standarized way than enter in a web page and solve some well known standard captchas.

With my approach, I can keep away >90% of userbots out of groups, just because to solve the captcha a developer needs to implement a not too standard way to resolve it. Another thing is, due my captchas generation are simple, it let me change and modify any parameters and behaviours to easily makes any automate captcha solver stop working properly. At last, due I own the captcha generation, It doesn't depend on a third party service that can be inaccessible or down some times.

I will keep this issue open, maybe I take a look into HCaptcha to see what offer.
If hcaptcha gives an accessible API that lets request and download the pair captcha and resolution data to use it at local, instead in a web server, it gives me the possibility to just stay in telegram and in a less standarized solve way...

Regards.
