### ISSUE TITLE
not all new users appear the captcha

### ISSUE THREAD

**Issue by AmidoNI2** [J-Rios/TLG_JoinCaptchaBot#34]
(sorry for bad english, is not my mother language)

on this print:
https://i.imgur.com/UOMK3Cz.png

we can see that but not showed the captcha, but the user tell to me that type the captcha appear and has been typed ok

every 10 users, 2 or 3 this thing occurs

**Comment by J-Rios** [comment]
Hi,

Note that Bot messages are automatically removed by the Bot after captcha process end, I assume that you know it and what you are describing is what you see at real time when a new user joins...

If some users can see the captcha messages but you don't, then the problem is in your Telegram client application (also, if you are the Admin of the group, yo should see all removed messages in "Recent Actions" option of group settings.

I recommend you to use an official telegram client. If you are using an official telegram application and the problem still happens, then try to reinstall the APP and/or contact Telegram Team.

Regards.

**Comment by AmidoNI2** [comment]
oh thank you for the up, you are correct and sorry for the opened issue.

here the recent message: 
![image](https://user-images.githubusercontent.com/61668748/77255744-800cf780-6c48-11ea-8439-a39c890f3d92.png)

the best verify bot 🗡
