### ISSUE TITLE
Customizable message after user completed captcha

### ISSUE THREAD

**Issue by victorperin** [J-Rios/TLG_JoinCaptchaBot#4]
I think customizing the message `CAPTHA_SOLVED` message to something like a group welcome message could be beneficial to some groups.

**Comment by J-Rios** [comment]
I have already received some messages about this, however there was telling me to send a welcome message **before** captcha to solve message (the one with numbers), so there is a discordance about what users want...

So, I will develop this functionality if a minimum of 50 persons respond to next poll (you can share it):
https://t.me/testjoincaptchabot/265

Anyway, I will accept pull request with that function if it is an extra functionality, so that pull request makes Bot works normally (same as today) and let to configure and enable/disable that welcome message with new implemented Bot commands.

**Comment by J-Rios** [comment]
Reached more than 50 votes, due poll result, a new customizable message after captcha completion has been implemented [[8bd8b41](https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/8bd8b41a4deb1d28cfa78df0b90d166fb47e65bc)].

A new welcome message that will be sent when each user complete the captcha can be configured with command /welcome_msg.

Enjoy this new feature.

**Comment by K0media** [comment]
@J-Rios, what about the post captcha solving message? Can that be customized too? Or will you leave it as is?

See if you can add the feature to customize that message too. It's quite self-explanatory, but it would be nice to have a `/post_solve_msg` command too, or something like that.

**Comment by J-Rios** [comment]
There was a [poll about it](https://t.me/groupjoincaptchabot/265).

Open a new Request issue if you want to ask for more customizable functionality and if anyone is interested in, can implement it (I am not xD).
