### ISSUE TITLE
Delete any message sent by the user if it's not solving the captcha

### ISSUE THREAD

**Issue by DarthJahus** [J-Rios/TLG_JoinCaptchaBot#5]
It would be nice to "mute" (delete all from) the new member until the captcha is solved.

For this, just delete any message that's not a solution to the captcha, and if it's a solution, then proceed accordingly.

It would also be good to choose whether to mute or kick (or even ban) users who don't solve captcha in the given time.

**Comment by J-Rios** [comment]
Hi,  

I was thinking about it when started Bot development... Finally, I let users to write messages before captcha completion cause it allows, to some people that doesn't understand captcha Bot, to ask other users of the group about how the captcha works.

Note that change this behaviour can be good/nice/better for some people, but it will make a lot of people disagree to it too.

So I'm not interested to change that behaviour, however I will accept pull request with that change only if it is an extra and optional functionality that can be enabled/disabled with new implemented commands (by default Bot must works as it do before the pull request, and "mute" users and select mute/kick/ban when captcha not solved can be configured and enabled with new commands).

Note for everyone:
This is a free software and open-source project, so please dont ask about change behaviour just because you "think is better", give me a good reason to do it, come with a poll result from more than 100 users that show what all of them thinks about that change. Otherwise, fork the project, modify what you want and create a new Bot account with your specific Bot characteristics for you, thanks.

Regards.

**Comment by DarthJahus** [comment]
Understood. Thank you. I'll add the feature whenever I have some time and make a pull request.

Regards.

**Comment by showTi** [comment]
I also want to have a BOT for Line.
