### ISSUE TITLE
The bot is down

### ISSUE THREAD

**Issue by ikovalyov** [J-Rios/TLG_JoinCaptchaBot#51]
![image](https://user-images.githubusercontent.com/3931179/85273409-da069e80-b47d-11ea-92d0-f06f7cbea767.png)

**Comment by J-Rios** [comment]
Experimenting some issue in Bot response time, due this, actual Bot instance has been shutdown.

Currently I'm trying to identify the reason of the issue...

**Comment by J-Rios** [comment]
Seems that the problem comes from the VPS network where the Bot instance was running. For some unknown reason there was something delaying telegram network packets reception.

Yesterday I have migrated the Bot instance to another VPS provider and all have been working normally until today. Let's give some more time (few days) of testing before closing the issue.

P.D. Also, I have been trying some performance stuffs ((Webhook support, Multithreads for message deletion and kick/ban funtions) into Bot code while trying to identify the problem. None of them fix the problem (due was a network issue), but I'm going to be testing and pushing this changes bit by bit.

**Comment by J-Rios** [comment]
So, no more delayed msgs, everything has been OK until today.

Let's close the issue.
