### ISSUE TITLE
[Request] Configure Bot group settings through private chat (similar to @MissRose_bot's functionality)

### ISSUE THREAD

**Issue by K0media** [J-Rios/TLG_JoinCaptchaBot#54]
@MissRose_bot has the feature to connect remotely to the desired group to manage the bot's settings. Being linked to the group, you can send and get commands by calling them privately, once it's connected to the group you need to do the alterations and management.

I'm currently using @join_captcha_bot because Rose lacks more features as yours have. And will probably keep it this way for some time since it suits my needs.

You can connect to the group remotely with the `/connect` command.

Example:
`/connect -1001235155926`

Which `-1001235155926` is the group `!id`.

Could that be possible?

Or you could integrate with Rose, by any chance... If that's even possible.

Thanks!

**Comment by J-Rios** [comment]
I'm not familiar with Rose Bot functionality... What you expect is to be able to config different groups from Bot private chat?

**Comment by K0media** [comment]
I see. Thanks for the info. I'll keep an eye here to see if people will agree with this idea or not.

However, iirc, there are some opensource bots that already have that open code to be "copied" and ported to other bots. I can provide more sources if needed.

PS: I'm not a programmer, but I might know a few basics.

**Comment by Marzal** [comment]
Shieldy allows to at least show the config of the bot in a group to not SPAM the group.

Not sure if the code could help some:

https://github.com/1inch/shieldy/blob/master/src/commands/viewConfig.ts

**Comment by J-Rios** [comment]
Thanks,

Problem here is not related to implementation, neither the needs of source code.The issue is related to what this feature internally involves...

If we want to configure a group from a Bot private conversation, then it must allow this configuration just by an Admin of that specific group, and not to anybody. Here, if we need to know if the user that speak to the Bot is an Admin of that group, then the Bot have two ways to handle this:

- **A)** Each time a user sends a config command, the Bot will request to Telegram Server the information of that group, and check if any of the Admins in the group is the current user that send the command. Of course, this is a really bad idea, due a "malicious user/userbot" could start sending private config command to the Bot making it send requests to Telegram, overflowing it and reaching Telegram flood restriction for this request.

- **B)** Makes Bot store groups Admins data. It could be in RAM and not stored, but just get it when an interaction occurs in the group. But then, sometime it won't be configurable through private chat due there has not been an interaction in the group after the Bot was rebooted. Or it could be in persistent memory, what is not really nice to store that info if it is not really useful (just for this feature is not enough justified reason, in my opinion).

Maybe the best way to implement this is go through **"A option"**, but implementing some kind of config command limitation that makes a user to won't be able to config something if it is not allowed to do in this group for some time (this will safe avoid the malicious floods).

Of course, just to show a group config doesn't needs to know if the user who ask is an Admin of that group, but then it seems more like a patch for a half way feature, that could conflict in the future if we implement some really private chat config behavior. It is related, but "show group info request" should be good to be placed in an independent issue and not in this one.

Best Regards.

**Comment by Marzal** [comment]
Thanks for the reply and the analysis (and obviously the bot).

If option A is consider along the road, I don't think that expending time in just "show group info" worth the time.

**Comment by J-Rios** [comment]
Yeah, I think it can be done in that way...

Maybe some kind of /manage command to setup the group that the user want to configure (here the Bot will check if it is a valid Admin) and then set the commands of the groups...

```text
/manage -1234567890
/time 1 min
/captcha_mode random
...
```

P.D. Thanks for the donation :heart:

**Comment by Marzal** [comment]
> Yeah, I think it can be done in that way...
> 
> Maybe some kind of /manage command to setup the group that the user want to configure (here the Bot will check if it is a valid Admin) and then set the commands of the groups...
> 
> ```
> /manage -1234567890
> /time 1 min
> /captcha_mode random
> ...
> ```
> 
> P.D. Thanks for the donation heart

Yeah, that would be great, I always send the commands in silent mode to not disturb the group, but the bot answers are normal messages so I try to be fast deleting the "conversation". This would be a great improvement.

PD: No hay de qué. Thanks again for the source code, the time and the online service (the bot itself).

**Comment by J-Rios** [comment]
> Yeah, that would be great, I always send the commands in silent mode to not disturb the group, but the bot answers are normal messages so I try to be fast deleting the "conversation". This would be a great improvement.

The Bot automatically delete the config messages after 1 min to keep a clean group, so there is no need to delete it manually (only if you want to remove before 1 min). Also, [Bot should be sending the messages in silent mode](https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/eda77cc83cb189c06bddff6cf37acffd0028aeea/sources/join_captcha_bot.py#L2553) (it was done as feature some time ago), maybe it is broken now and is sending as normal messages?

**Comment by Marzal** [comment]
> > Yeah, that would be great, I always send the commands in silent mode to not disturb the group, but the bot answers are normal messages so I try to be fast deleting the "conversation". This would be a great improvement.
> 
> The Bot automatically delete the config messages after 1 min to keep a clean group, so there is no need to delete it manually (only if you want to remove before 1 min). Also, [Bot should be sending the messages in silent mode](https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/eda77cc83cb189c06bddff6cf37acffd0028aeea/sources/join_captcha_bot.py#L2553) (it was done as feature some time ago), maybe it is broken now and is sending as normal messages?

I will test again.
I did the testing a long time ago (with another account), probably before April 2020. So it's totally possible that it's an old habit no longer necessary

**Comment by J-Rios** [comment]
Ok, then it must be revised.

Please  let's use this new issue regarding the silent messages to keep a good track of the problem in a specific issue:
https://github.com/J-Rios/TLG_JoinCaptchaBot/issues/118

Regards.

**Comment by J-Rios** [comment]
Done, configure Bot group settings through private chat feature implemented and added in:
https://github.com/J-Rios/TLG_JoinCaptchaBot/commit/7c6a99570667d3ba73b8f27f8e54a532ec69b687

## How-To

1 - Use /chatid inside the group you want to configure to get the "Group Chat ID".

```text
/chatid
```

2 - Open a private chat conversation with the Bot and use /connect command to bind the private chat to configure that group (i.e. if the group chat ID is -1234567890):

```text
/connect -1234567890
```

3 - Now you can configure everything you want of the group:

```text
/time 1
/language es
/captcha_mode random
```

4 - Disconnect from the group once done:

```text
/disconnect
```

Regards.
