### ISSUE TITLE
spammer learnt, now they use forwarding

### ISSUE THREAD

**Issue by bertothunder** [J-Rios/TLG_JoinCaptchaBot#6]
Spammers have evolved, and now they forward messages from their own channels without passing the captcha.

Bot should block *any* message from the user until it resolves the captcha.

**Comment by J-Rios** [comment]
Bot is already blocking any message that contains an URL or alias, even forwarded messages, this issue was solved some time ago... I can't replicate the issue, please if you see it again, show how to exactly replicate this issue.

About block any (all) messages of new users until captcha solve: I let users to write messages before captcha completion cause it allows, to some people that doesn't understand captcha Bot, to ask other users of the group about how the captcha works, I see it a lot and is really usefull.

**Comment by danielthegray** [comment]
Maybe it would be a good configuration parameter to add?

**Comment by J-Rios** [comment]
I will considere in a future to add a new command to configure and keep Bot removing any message from users that doesn't solve the captcha in each group, not in my priority list right now.
