### ISSUE TITLE
[Issue] Fail delete spam message with t.me url

### ISSUE THREAD

**Issue by pratamawijaya** [J-Rios/TLG_JoinCaptchaBot#97]
I noticed new variance of spam message coming to my group

sample message and bot response 
![bot_tele_fail](https://user-images.githubusercontent.com/2455823/118635347-ac48e780-b7fd-11eb-8bc4-033af5a25c0b.png)

and bot fail to delete message
![bot_tele_fail_2](https://user-images.githubusercontent.com/2455823/118635377-b539b900-b7fd-11eb-9c5b-55f9695c7194.png)

i want to contribute, but i dont know how to fix it, i have check your source code, 

its around here https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/master/sources/join_captcha_bot.py#L324 

and i have check https://github.com/J-Rios/TLG_JoinCaptchaBot/blob/master/sources/tlds-alpha-by-domain.txt too,

but still doesnt have idea how to solve it, because python isnt my primary programming language

**Comment by J-Rios** [comment]
Hi,

That URL message can be detected as Spam from Bot code without any problem...

Your issue seems to be caused due that Bot instance deployed ("Banglago") is too slow to detect the "new user joins the group" event, and any spam message received before the Bot know that it is a new user won't be considered Spam (the Bot didn't know that it is a new user yet due it is to slow!).

So, check your deploy network latency/delays, check firewalls, proxies, deploy the Bot with a Webhook instead polling, etc.

**Comment by pratamawijaya** [comment]
ok, thanks for the advice @J-Rios i will change my bot instance to webhook
